#+TITLE: fipar.github.io 
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="style.css" />
* Contact 
You can email me at fipar(at)acm(dot)org, or find me on freenode as
fipar or nandix.  

You can also contact me at [[http://linkedin.com/in/fipar][Linkedin]].

I am not on any other social network, though you will find people on
Twitter and Facebook with my same name, and also from Uruguay. You'd
be confused if you follow them expecting to get updates from me. 

* Work
I currently work at Percona as a [[https://www.percona.com/about-us/our-team/fernando-ipar
][Senior Consultant]].
* Blog 
I have a [[http://fernandoipar.com][personal blog]] (with mostly technical oriented content), and I
also contributed to [[https://www.percona.com/blog/author/fernando/][Percona's Blog]].
* Code
I have not been working as a full time programmer for a few years now,
but you can still find some repos with my code here: 
- http://github.com/fipar/ 
- https://launchpad.net/~fipar
- http://www.ohloh.net/accounts/nandix
- http://sourceforge.net/users/fipar/ (unmaintained)
* Interests
I focus on Database Performance, with an emphasis on MySQL and
MongoDB, though I also work with other Open Source databases depending
on customer's needs. 

In relation to this, I am very interested in Systems Performance
Analysis, and I'm a big fan of [[http://brendangregg.com][Brendan Gregg]] (for insight on analysis)
and [[http://www.edwardtufte.com/tufte/][Edward Tufte]] (for insight on data visualization).  

I'm also very interested in programming. For the past few years, I have
mostly done that as part of consulting engagements, using bash, Ruby
and Go, but beyond my job, I engage in programming for fun, using
those languages, plus lisp (mostly CL and Clojure). I also enjoy
solving small problems (meaning things you can complete in a Saturday
morning) using other languages such as Erlang or Haskell, just to keep
the brain in shape. 

I'm a happy owner of a Boxed Set of Knuth's [[http://www-cs-faculty.stanford.edu/~uno/taocp.html][The Art of Computer
Programming]], and have been going through the exercises slowly, in my
spare time, for the last few years. I have mostly been focusing on
Volumes 1 and 3 for now. 
