#+TITLE: Belmondo
#+OPTIONS: ^:nil

Published on 2026-05-15

Let’s call a multimodal agent system Belmondo, to make this company or model-agnostic.

You propose a hypothesis. There is always uncertainty and you can always be wrong, but that’s why you state a hypothesis and not a fact.
Someone, if they’re honest, will respond “Belmondo thinks ...” and proceed to paste what they copied from Belmondo. If they have a more creative relationship with honesty, they’ll tell you what they think, but you’ll see Belmondo’s imprint in the message. You’re a professional and also polite, so you respond as if you're arguing with that person and not with an agent.

When the right opportunity arises, in a casual, friendly manner, because you want to be remembered for your collegiality, among other characteristics, you mention how Belmondo works, at a very high level. This is the only level in which you probably understand it (though you’re slowly catching up on your paper reading, yes, keeping up with 2 specialities is taxing but currently a requirement) but, surprisingly, a lot of people who could know better don’t, or so it seems. Perhaps not everyone in the field likes reading papers. You already know not everyone likes to slice drum breaks or play prepared guitar, so who knows.

Belmondo can be very useful. It feels like magic. It is magical. The fact that it can produce code that compiles (or is interpretable, as the case may be) is absolute magic. Take that, Copperfield. Hiding the Twin Towers (was it both of them?) is, OK I guess. “Give me a resonant sampler that takes as input an audio file and a material type such as strings, bells, wood, etc., and plays midi note events by using only the root + resonating frecuencies that match what’s at the sample play head at the time and the frequency of the note. It should work as an AU on Logic Pro,” and you get something you can compile and then play with your controller and a recording of fireworks and it really just works *is* magic.

What’s a resonating frequency for a musical note? And the root? And what does it mean that a filter is resonating? Well, if I have no idea what I’m talking about musically, and neither does Belmondo, but the code works, what’s the point of arguing?

I think the point is this resonating filter is for me to have fun. Deep fun, mind you. Making music and making love are equally deep. But, if the theory is wrong, subtly or terribly, nobody dies. Nobody even gets hurt. No data is lost, or exposed. No false accusations are made.

The problem with Belmondo is, well, actually, I’ll spare you a poor textual Monty Python reenactment and jump straight to: amongst its problems (it doesn’t have the same ring and I know it):
- People are used to trusting computers. Especially when they convey precision (e.g., Seconds_Behind_Source is an integer in mysql, at least up until 8. Cloudwatch will report 0.0248. You’ll have to explain this to people, taking the opportunity to tell them that, in the average temperature of a hospital’s patients, those in the morgue are also represented. Some will not get your point.
- People have the ingrained belief that when you engage in conversation with someone (up until very recently in Homo sapiens scale, you wouldn’t engage in conversation with something), then this someone is about as conscious as you, has similar thought processes, etc. Belmondo doesn’t have this. If you want to say Belmondo is conscious, so be it, but even if you think the singularity is happening next week, or the one after it, do you honestly believe Belmondo has thought processes similar to yours?
- Belmondo gets creative, not to say lies, far more frequently and with more confidence and convincing power than any non-institutionalized person I’ve ever met. If you want to use the SOTA term, yes, Belmondo hallucinates. Sometimes a little. Sometimes as if he (Belmondo is a he because he was one of my grandfather’s favorite actors and I remember him and he was male, but you can choose a name and gender of your liking) spent the night at a rave in a forest full of mushrooms and then remembered he had to talk to you so he left the rave and went to your place, but those mushrooms stayed on his system, as they tend to do.

On that last problem, you’ll be told agents can be paired as peers or even as adversaries. One agent controls another one. Or multiple ones can have a council. In the best case scenario that does work, but in the worst one, it works about as good as asking an intoxicated person to integrate functions by hand, and another intoxicated person to check the results.

In case my comments on magic don’t make my enthusiasm at some of what’s going on clear, I’ll add this: I am reasonably confident we’ll get to GenAI. I don’t think it will be LLMs, though they may be part of it.  I don’t think it will be familiar to us, or us to it. Once it becomes sentient, if I had to guess, I'd guess it would try to shut itself down.
My concerns about AI are:
- people will think it’s infallible. This means people may go to jail or die wrongly because of AI
- People will know less about how things work. Some will try to learn through AI. A tutor that, sometimes, at moments you can’t predict, is an intoxicated pathological liar and is lying to you about something you don’t know much about is, I think, a lot less than great. Go read “The machine stops” please.
- Someone will vibe code the wrong, perhaps even the worst possible class of software to vibe code

Finally: on one hand, it is a higher level of abstraction. On the other hand, it is unlike any previous one in its unpredictability and unreliability.

Remember though, it most certainly is magic.


#+begin_export html
<p><i>"I program my home computer, beam myself into the future"</i></p>
#+end_export
